/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BotondBencsik (https://sketchfab.com/bosch00)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fuseboxa-0599adf4e47e4ed5966a54cdd2301715
Title: FuseboxA
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function FuseModel({ onModelReady, ...props }) {
  const { nodes, materials } = useGLTF("models/fuseboxa.glb");
  const groupRef = useRef();

  useEffect(() => {
    if (groupRef.current && onModelReady) {
      // Pass the group reference to the parent component
      onModelReady(groupRef.current);
    }
  }, [onModelReady]);

  return (
    <group {...props} dispose={null}>
      <group
        ref={groupRef}
        scale={[0, 0, 0]} // Adjusted scale
        rotation={[10, 0, 0]} // Rotate 180 degrees around Y axis
        position={[0, 0, 0]} // Reset position
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object285_PartsB_0.geometry}
          material={materials.PartsB}
          position={[-2.74, 3.359, 0.168]}
        />
      </group>
      <group
        position={[14.689, 1.235, -9.543]}
        rotation={[-Math.PI / 2, 0, -2.705]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object286_PartsB_0.geometry}
          material={materials.PartsB}
          position={[-2.74, 3.359, 0.168]}
        />
      </group>
      <group position={[15.202, 1.749, -5.645]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object287_PartsB_0.geometry}
          material={materials.PartsB}
          position={[-2.74, 3.359, 0.168]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.aPartsLO001_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 6.988, -31.129]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box081_PartsC_0.geometry}
        material={materials.PartsC}
        position={[0.18, 0.019, -3.062]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box082_PartsA_0.geometry}
        material={materials.PartsA}
        position={[0.118, -0.031, -5.941]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box083_PartsB_0.geometry}
        material={materials.PartsB}
        position={[8.362, 10.426, -10.821]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box084_PartsB_0.geometry}
        material={materials.PartsB}
        position={[8.362, 17.96, -10.821]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box085_PartsB_0.geometry}
        material={materials.PartsB}
        position={[3.708, 18.702, -9.173]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box086_PartsB_0.geometry}
        material={materials.PartsB}
        position={[3.709, 21.702, -8.656]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box087_PartsB_0.geometry}
        material={materials.PartsB}
        position={[5.264, 18.702, -9.173]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box088_PartsB_0.geometry}
        material={materials.PartsB}
        position={[5.264, 21.702, -8.656]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box089_PartsB_0.geometry}
        material={materials.PartsB}
        position={[6.822, 18.702, -9.173]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box090_PartsB_0.geometry}
        material={materials.PartsB}
        position={[6.823, 21.702, -8.656]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box091_PartsB_0.geometry}
        material={materials.PartsB}
        position={[8.367, 18.702, -9.173]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box092_PartsB_0.geometry}
        material={materials.PartsB}
        position={[8.368, 21.702, -8.656]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box093_PartsB_0.geometry}
        material={materials.PartsB}
        position={[9.91, 18.702, -9.173]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box094_PartsB_0.geometry}
        material={materials.PartsB}
        position={[9.911, 21.702, -8.656]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box095_PartsB_0.geometry}
        material={materials.PartsB}
        position={[11.448, 18.702, -9.173]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box096_PartsB_0.geometry}
        material={materials.PartsB}
        position={[11.448, 21.702, -8.656]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box097_PartsB_0.geometry}
        material={materials.PartsB}
        position={[12.997, 18.702, -9.173]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box098_PartsB_0.geometry}
        material={materials.PartsB}
        position={[12.997, 21.702, -8.656]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box100_PartsC_0.geometry}
        material={materials.PartsC}
        position={[16.834, 23.617, 1.428]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bPartsLO001_PartsB_0.geometry}
        material={materials.PartsB}
        position={[8.299, 27.527, -9.334]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cPartsLO007_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 36.536, -9.296]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cPartsLO008_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 31.955, -9.296]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cPartsLO009_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 27.36, -9.296]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cPartsLO010_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 22.778, -9.296]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cPartsLO011_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 18.194, -9.296]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cPartsLO012_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 13.614, -9.296]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cPartsLO013_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 9.05, -9.296]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder166_PartsA_0.geometry}
        material={materials.PartsA}
        position={[0.03, 53.847, -6.037]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder167_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-11.593, 41.175, -6.256]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder168_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.149, 36.06, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder169_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.281, 36.06, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder170_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.42, 39.618, -6.289]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder171_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.02, 39.618, -6.289]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder172_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.112, 10.094, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder173_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.377, 10.094, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder174_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.112, 14.721, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder175_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.377, 14.721, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder176_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.112, 19.258, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder177_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.377, 19.258, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder178_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.112, 23.866, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder179_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.377, 23.866, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder180_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.112, 28.427, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder181_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.377, 28.427, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder182_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.112, 33.026, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder183_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.377, 33.026, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder184_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.112, 37.586, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder185_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.377, 37.586, -6.146]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder186_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-5.774, 41.175, -6.256]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder187_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.149, 31.479, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder188_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.281, 31.479, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder189_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.149, 26.885, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder190_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.281, 26.885, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder191_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.149, 22.303, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder192_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.281, 22.303, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder193_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.149, 17.718, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder194_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.281, 17.718, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder195_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.149, 13.138, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder196_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.281, 13.138, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder197_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-3.149, 8.574, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder198_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-14.281, 8.574, -6.261]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder199_PartsC_0.geometry}
        material={materials.PartsC}
        position={[19.948, 46.488, -13.27]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder200_PartsA_0.geometry}
        material={materials.PartsA}
        position={[10.764, 50.526, -2.85]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder201_PartsA_0.geometry}
        material={materials.PartsA}
        position={[10.764, 50.526, -9.04]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder202_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-10.636, 50.526, -2.85]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder203_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-10.636, 50.526, -9.04]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder204_PartsA_0.geometry}
        material={materials.PartsA}
        position={[10.764, -0.541, -2.85]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder205_PartsA_0.geometry}
        material={materials.PartsA}
        position={[10.764, -0.541, -9.04]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder206_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-10.636, -0.541, -2.85]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder207_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-10.636, -0.541, -9.04]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder208_PartsA_0.geometry}
        material={materials.PartsA}
        position={[20.21, 3.408, -12.847]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder209_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-20.789, 3.408, -12.847]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder210_PartsA_0.geometry}
        material={materials.PartsA}
        position={[20.21, 46.488, -12.847]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder211_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-20.789, 46.488, -12.847]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder212_PartsA_0.geometry}
        material={materials.PartsA}
        position={[4.027, 15.303, -9.642]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder213_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-18.591, 5.927, 1.739]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder214_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-18.591, 44.119, 1.739]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder215_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-18.591, 34.932, 1.739]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder216_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-18.591, 15.1, 1.739]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder217_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-18.591, 25.091, 1.739]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line033_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-0.173, 39.526, -7.448]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line034_PartsA_0.geometry}
        material={materials.PartsA}
        position={[1.541, 46.825, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line035_PartsA_0.geometry}
        material={materials.PartsA}
        position={[16.951, 29.533, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line036_PartsA_0.geometry}
        material={materials.PartsA}
        position={[7.789, 16.13, -8.844]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line037_PartsA_0.geometry}
        material={materials.PartsA}
        position={[2.047, -5.881, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line038_PartsA_0.geometry}
        material={materials.PartsA}
        position={[4.47, 16.13, -8.844]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line039_PartsA_0.geometry}
        material={materials.PartsA}
        position={[11.227, 19.407, -3.229]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object203_PartsA_0.geometry}
        material={materials.PartsA}
        position={[3.915, 26.928, -7.215]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object204_PartsA_0.geometry}
        material={materials.PartsA}
        position={[3.426, 51.95, -7.215]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object205_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 36.483, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object206_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 36.483, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object207_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-2.615, 35.013, -6.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object208_PartsA_0.geometry}
        material={materials.PartsA}
        position={[0.01, -1.213, -5.995]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object209_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 31.901, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object210_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 31.901, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object211_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-2.615, 30.432, -6.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object212_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 27.307, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object213_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 27.307, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object214_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-2.615, 25.837, -6.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object215_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 22.725, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object216_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 22.725, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object217_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 22.725, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object218_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-2.615, 21.255, -6.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object219_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 18.14, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object220_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 18.141, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object221_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 18.14, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object222_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-2.615, 16.67, -6.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object223_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 13.561, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object224_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 13.561, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object225_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 13.561, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object226_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-2.615, 12.091, -6.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object227_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 8.997, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object228_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 8.997, -7.957]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object229_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-2.615, 7.527, -6.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object230_PartsA_0.geometry}
        material={materials.PartsA}
        position={[0.343, -11.256, -16.611]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object232_plastic_0.geometry}
        material={materials.plastic}
        position={[4.029, 15.309, -9.582]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object233_PartsB_0.geometry}
        material={materials.PartsB}
        position={[3.708, 20.391, -8.269]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape005_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-0.173, 39.526, -7.448]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object234_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-14.218, 18.141, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object235_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 8.988, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object236_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-14.218, 8.988, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object237_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-8.718, 27.296, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object238_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-14.218, 27.296, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object239_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-14.218, 31.893, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object240_PartsB_0.geometry}
        material={materials.PartsB}
        position={[-14.218, 36.489, -7.311]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box101_PartsC_0.geometry}
        material={materials.PartsC}
        position={[-79.557, 0.019, 26.588]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box102_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-79.619, -0.031, 23.709]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder218_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-79.707, 53.847, 23.613]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder251_PartsC_0.geometry}
        material={materials.PartsC}
        position={[-59.789, 46.488, 16.38]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder252_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-68.973, 50.526, 26.799]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder253_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-68.973, 50.526, 20.61]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder254_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-90.373, 50.526, 26.799]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder255_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-90.373, 50.526, 20.61]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder256_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-68.973, -0.541, 26.799]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder257_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-68.973, -0.541, 20.61]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder258_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-90.373, -0.541, 26.799]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder259_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-90.373, -0.541, 20.61]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder260_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-59.527, 3.408, 16.803]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder261_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-100.526, 3.408, 16.803]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder262_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-59.527, 46.488, 16.803]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder263_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-100.526, 46.488, 16.803]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder265_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-98.328, 5.927, 31.389]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder266_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-98.328, 44.119, 31.389]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder267_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-98.328, 34.932, 31.389]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder268_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-98.328, 15.1, 31.389]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder269_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-98.328, 25.091, 31.389]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line044_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-77.69, -5.881, 29.65]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object242_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-76.311, 51.95, 22.435]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object246_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-79.727, -1.213, 23.655]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object268_PartsA_0.geometry}
        material={materials.PartsA}
        position={[-79.394, -11.256, 13.039]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_display_0.geometry}
        material={materials.display}
        position={[9.326, 34.861, -5.301]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object279_PartsB_0.geometry}
        material={materials.PartsB}
        position={[5.267, 20.391, -8.269]}
        rotation={[-2.443, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object280_PartsB_0.geometry}
        material={materials.PartsB}
        position={[6.823, 20.391, -8.269]}
        rotation={[-2.443, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object281_PartsB_0.geometry}
        material={materials.PartsB}
        position={[8.373, 20.391, -8.269]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object282_PartsB_0.geometry}
        material={materials.PartsB}
        position={[9.925, 20.391, -8.269]}
        rotation={[-2.443, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object283_PartsB_0.geometry}
        material={materials.PartsB}
        position={[11.456, 20.391, -8.269]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object284_PartsB_0.geometry}
        material={materials.PartsB}
        position={[13.005, 20.391, -8.269]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object288_PartsC_0.geometry}
        material={materials.PartsC}
        position={[-18.577, 4.379, 1.809]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object289_PartsC_0.geometry}
        material={materials.PartsC}
        position={[-98.314, 4.379, 31.458]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder271_PartsC_0.geometry}
        material={materials.PartsC}
        position={[5.29, 29.372, -3.473]}
        scale={0.277}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box120_redON_0.geometry}
        material={materials.redON}
        position={[3.709, 21.695, -8.504]}
        scale={[0.34, 0.308, 0.141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box121_greenOff_0.geometry}
        material={materials.greenOff}
        position={[5.266, 21.695, -8.504]}
        scale={[0.34, 0.308, 0.141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box122_greenOff_0.geometry}
        material={materials.greenOff}
        position={[6.823, 21.695, -8.504]}
        scale={[0.34, 0.308, 0.141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box123_redON_0.geometry}
        material={materials.redON}
        position={[8.358, 21.695, -8.504]}
        scale={[0.34, 0.308, 0.141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box124_greenOff_0.geometry}
        material={materials.greenOff}
        position={[9.901, 21.695, -8.504]}
        scale={[0.34, 0.308, 0.141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box125_redON_0.geometry}
        material={materials.redON}
        position={[11.43, 21.695, -8.504]}
        scale={[0.34, 0.308, 0.141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box126_redON_0.geometry}
        material={materials.redON}
        position={[13.006, 21.695, -8.504]}
        scale={[0.34, 0.308, 0.141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004_PartsC_0.geometry}
        material={materials.PartsC}
        position={[-5.75, 39.754, -5.757]}
        scale={[0.031, 0.031, 0.017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005_PartsC_0.geometry}
        material={materials.PartsC}
        position={[-11.587, 39.754, -5.757]}
        scale={[0.031, 0.031, 0.017]}
      />
    </group>
  );
}

useGLTF.preload("/fuseboxa.glb");
