/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: GeniusPilot2016 (https://sketchfab.com/GeniusPilot2016)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/led-floodlight-08e8bb8137934f3a8c55c2c8555d92ef
Title: LED Floodlight
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LedModel({ onModelReady, ...props }) {
  const { nodes, materials } = useGLTF("models/led_floodlight.glb");
  const groupRef = useRef();

  useEffect(() => {
    if (groupRef.current && onModelReady) {
      // Pass the group reference to the parent component
      onModelReady(groupRef.current);
    }
  }, [onModelReady]);
  return (
    <group {...props} dispose={null}>
      <group
        ref={groupRef}
        scale={[1.5, 1.5, 1.5]} // Adjusted scale
        rotation={[5, 0, 0]} // Rotate 180 degrees around Y axis
        position={[0, 1, 0]} // Reset position
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.body}
        />
        <group
          position={[0.001, -0.932, 0.637]}
          rotation={[-0.611, 0, 0]}
          scale={6.25}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.tempered_glass}
          />
          <group
            position={[-0.204, -0.02, -0.094]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.16}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.led_base}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials["phosphorus.002"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.nuts}
            position={[0.255, -0.18, -0.002]}
            rotation={[2.182, 0, -Math.PI / 2]}
            scale={0.16}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials.material_base}
            position={[0, -0.046, -0.167]}
            scale={[0.276, 0.16, 0.202]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/led_floodlight.glb");
