/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LightModel(props) {
  const { nodes, materials } = useGLTF('/ImageToStl.com_LighPole.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.MetalBlack}
        position={[0, 15, 0]}
        scale={[0.5, 15, 0.5]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bolt.geometry}
          material={materials.Bolts}
          position={[0.008, -0.989, -1.504]}
          scale={[0.066, 0.002, 0.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bolt001.geometry}
          material={materials.Bolts}
          position={[0.008, -0.989, 1.522]}
          scale={[0.066, 0.002, 0.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bolt002.geometry}
          material={materials.Bolts}
          position={[-1.505, -0.989, 0.009]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.066, 0.002, 0.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bolt003.geometry}
          material={materials.Bolts}
          position={[1.521, -0.989, 0.009]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.066, 0.002, 0.066]}
        />
        <group position={[0, 1.029, 0]} scale={[2, 0.021, 1.341]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials.MetalBlack}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials.Glass}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.MetalBlack}
          position={[0, -1, 0]}
          scale={[2, 0.067, 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials.MetalBlack}
          position={[0, 0.969, 0]}
          scale={[2, 0.067, 2]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[-0.072, -0.155, 0.049]}
        rotation={[Math.PI, 0, 0]}
        scale={[-52.385, -0.084, -55.549]}
      />
    </group>
  )
}

useGLTF.preload('/ImageToStl.com_LighPole.glb')