/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: clon6767 (https://sketchfab.com/clon6767)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electric-box-set1-ef67fcf75a77492b90ec70184123f393
Title: electric_box_set1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MainBoxModel(props) {
  const { nodes, materials } = useGLTF('models/electric_box_set1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.lambert4SG_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.lambert3SG_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.lambert3SG_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.lambert3SG_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.lambert3SG_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.lambert2SG_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.initialShadingGroup_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_7.geometry}
            material={materials.initialShadingGroup_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_8.geometry}
            material={materials.initialShadingGroup_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_9.geometry}
            material={materials.initialShadingGroup_1001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_10.geometry}
            material={materials.initialShadingGroup_1001}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/electric_box_set1.glb')