/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: youssef-hamdan (https://sketchfab.com/youssef-hamdan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-panel-fbx-bb49ffe079064a46986edafd067dd8e3
Title: Solar panel FBX
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

export function SolarModel({ onModelReady, ...props }) {
  const { nodes, materials } = useGLTF("models/solar_panel_fbx.glb");
  const groupRef = useRef();

  useEffect(() => {
    if (groupRef.current && onModelReady) {
      // Pass the group reference to the parent component
      onModelReady(groupRef.current);
    }
  }, [onModelReady]);

  return (
    <group {...props} dispose={null}>
      <group
        ref={groupRef}
        scale={[2, 2, 2]} // Adjusted scale
        rotation={[10, 0, 0]} // Rotate 180 degrees around Y axis
        position={[0, 100, 0]} // Reset position
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material_0.geometry}
          material={materials.Material}
          position={[0, 50, 0]}
          rotation={[0, 0, 0]}
          scale={[85, 5, 100]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/solar_panel_fbx.glb");
